openapi: 3.0.1
info:
  description: "OAS 3.0.1 definition of the Performance Threshold Monitoring MnS ©\
    \ 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).\
    \ All rights reserved."
  title: TS 28.532 Performance Threshold Monitoring MnS
  version: 17.1.0
externalDocs:
  description: 3GPP TS 28.532; Generic management services
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.532/
servers:
- url: "{root}"
  variables:
    root:
      default: http://example.com/3GPPManagement
      description: "The open API server of the performance threshold monitoring service\
        \ is located in the consumer side, see monitoringNotifTarget attribute of\
        \ the IOC ThresholdMonitor defined in 3GPP TS 28.622 [11]. "
paths:
  /notificationSink:
    post:
      description: To send a notifyThresholdCrossing notification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyThresholdCrossing'
        required: true
      responses:
        "204":
          description: Success case ("204 No Content"). The notification is successfully
            delivered. The response message body is absent.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Send notifications about performance threshold crossing
components:
  schemas:
    PerfNotificationTypes:
      enum:
      - notifyThresholdCrossing
      type: string
    PerfMetricValue:
      oneOf:
      - type: integer
      - $ref: '#/components/schemas/Float'
    PerfMetricDirection:
      enum:
      - UP
      - DOWN
      type: string
    NotifyThresholdCrossing:
      allOf:
      - $ref: '#/components/schemas/NotificationHeader'
      - $ref: '#/components/schemas/NotifyThresholdCrossing_allOf'
    ErrorResponse:
      description: Default schema for the response message body in case the request
        is not successful.
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse_error'
      type: object
    Float:
      format: float
      type: number
    NotificationHeader:
      properties:
        href:
          type: string
        notificationId:
          type: integer
        notificationType:
          $ref: '#/components/schemas/NotificationType'
        eventTime:
          format: date-time
          type: string
        systemDN:
          type: string
      required:
      - eventTime
      - href
      - notificationId
      - notificationType
      - systemDN
      type: object
      x-parent: true
    Uri:
      type: string
    NotificationId:
      type: integer
    NotificationType:
      oneOf:
      - $ref: '#/components/schemas/AlarmNotificationTypes'
      - $ref: '#/components/schemas/CmNotificationTypes'
      - $ref: '#/components/schemas/PerfNotificationTypes'
      - $ref: '#/components/schemas/HeartbeatNotificationTypes'
      - $ref: '#/components/schemas/FileNotificationTypes'
    DateTime:
      format: date-time
      type: string
    SystemDN:
      type: string
    AlarmNotificationTypes:
      enum:
      - notifyNewAlarm
      - notifyChangedAlarm
      - notifyChangedAlarmGeneral
      - notifyAckStateChanged
      - notifyCorrelatedNotificationChanged
      - notifyComments
      - notifyClearedAlarm
      - notifyAlarmListRebuilt
      - notifyPotentialFaultyAlarmList
      type: string
    CmNotificationTypes:
      enum:
      - notifyMOICreation
      - notifyMOIDeletion
      - notifyMOIAttributeValueChanges
      - notifyMOIChanges
      type: string
    HeartbeatNotificationTypes:
      enum:
      - notifyHeartbeat
      type: string
    FileNotificationTypes:
      enum:
      - notifyFileReady
      - notifyFilePreparationError
      type: string
    NotifyThresholdCrossing_allOf:
      properties:
        observedPerfMetricName:
          type: string
        observedPerfMetricValue:
          $ref: '#/components/schemas/PerfMetricValue'
        observedPerfMetricDirection:
          $ref: '#/components/schemas/PerfMetricDirection'
        thresholdValue:
          $ref: '#/components/schemas/PerfMetricValue'
        hysteresis:
          $ref: '#/components/schemas/PerfMetricValue'
        monitorGranularityPeriod:
          type: integer
        additionalText:
          type: string
      type: object
      example: null
    ErrorResponse_error:
      properties:
        errorInfo:
          type: string
      type: object
