/*
Neasdf_DNSContext

EASDF DNS Context Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_Neasdf_DNSContext

import (
	"encoding/json"
)

// checks if the BaselineDnsMdtId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaselineDnsMdtId{}

// BaselineDnsMdtId Baseline DNS Message Detection Template Identifier
type BaselineDnsMdtId struct {
	BaseDnsPatternUri []string `json:"baseDnsPatternUri"`
	MdtId             string   `json:"mdtId"`
}

// NewBaselineDnsMdtId instantiates a new BaselineDnsMdtId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaselineDnsMdtId(baseDnsPatternUri []string, mdtId string) *BaselineDnsMdtId {
	this := BaselineDnsMdtId{}
	this.BaseDnsPatternUri = baseDnsPatternUri
	this.MdtId = mdtId
	return &this
}

// NewBaselineDnsMdtIdWithDefaults instantiates a new BaselineDnsMdtId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaselineDnsMdtIdWithDefaults() *BaselineDnsMdtId {
	this := BaselineDnsMdtId{}
	return &this
}

// GetBaseDnsPatternUri returns the BaseDnsPatternUri field value
func (o *BaselineDnsMdtId) GetBaseDnsPatternUri() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BaseDnsPatternUri
}

// GetBaseDnsPatternUriOk returns a tuple with the BaseDnsPatternUri field value
// and a boolean to check if the value has been set.
func (o *BaselineDnsMdtId) GetBaseDnsPatternUriOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseDnsPatternUri, true
}

// SetBaseDnsPatternUri sets field value
func (o *BaselineDnsMdtId) SetBaseDnsPatternUri(v []string) {
	o.BaseDnsPatternUri = v
}

// GetMdtId returns the MdtId field value
func (o *BaselineDnsMdtId) GetMdtId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MdtId
}

// GetMdtIdOk returns a tuple with the MdtId field value
// and a boolean to check if the value has been set.
func (o *BaselineDnsMdtId) GetMdtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MdtId, true
}

// SetMdtId sets field value
func (o *BaselineDnsMdtId) SetMdtId(v string) {
	o.MdtId = v
}

func (o BaselineDnsMdtId) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaselineDnsMdtId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["baseDnsPatternUri"] = o.BaseDnsPatternUri
	toSerialize["mdtId"] = o.MdtId
	return toSerialize, nil
}

type NullableBaselineDnsMdtId struct {
	value *BaselineDnsMdtId
	isSet bool
}

func (v NullableBaselineDnsMdtId) Get() *BaselineDnsMdtId {
	return v.value
}

func (v *NullableBaselineDnsMdtId) Set(val *BaselineDnsMdtId) {
	v.value = val
	v.isSet = true
}

func (v NullableBaselineDnsMdtId) IsSet() bool {
	return v.isSet
}

func (v *NullableBaselineDnsMdtId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaselineDnsMdtId(val *BaselineDnsMdtId) *NullableBaselineDnsMdtId {
	return &NullableBaselineDnsMdtId{value: val, isSet: true}
}

func (v NullableBaselineDnsMdtId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaselineDnsMdtId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
