openapi: 3.0.1
info:
  description: "OAS 3.0.1 specification of the Performance Measurement Job Control\
    \ Service @ 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI,\
    \ TTA, TTC). All rights reserved."
  title: TS 28.550 Performance Measurement Job Control Service
  version: 16.8.0
externalDocs:
  description: 3GPP TS 28.550 V16.8.0; Performance assurance
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.550/
servers:
- url: "{MnSRoot}/PerfMeasJobCtrlMnS/{MnSVersion}"
  variables:
    MnSRoot:
      default: http://example.com/3GPPManagement
      description: See clause 4.4.2 of TS 32.158
    MnSVersion:
      default: XXX
      description: Version number of the OpenAPI definition
paths:
  /measJobs:
    get:
      description: "With HTTP GET, resources of measurement jobs are read. The resources\
        \ to be read are identified with the path component (base resource) and the\
        \ query component (jobIdList) of the URI. The fields query component allows\
        \ to select the resource properties to be returned."
      parameters:
      - description: This parameter identifies the list of jobId to select the resources
          from the collection resources identified with the path component of the
          URI.
        explode: true
        in: query
        name: jobIdList
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/measJobsRetrieval-ResponseType'
          description: "Success case (\"200 OK\"). The resources identified in the\
            \ request for retrieval are returned in the response message body. In\
            \ case the fields query parameter is used, the selected resources are\
            \ returned."
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-ResponseType'
          description: Error case.
      summary: Read resources of measurement jobs
    post:
      description: To create a measurement job the representation of the measurement
        job is POSTed on the /measJobs collection resource.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/measJobCreation-RequestType'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/measJobCreation-ResponseType'
          description: Success case ("201 Created"). The representation of the newly
            created measurement job resource shall be returned.
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/measJobCreation-ResponseType'
          description: Partial success case ("202 Partically created"). The representation
            of the newly created measurement job resource with unsupported list shall
            be returned.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-ResponseType'
          description: Error case.
      summary: Create a measurement job
  /measJobs/{jobId}:
    delete:
      description: The measurement job is deleted by deleting the corresponding measurement
        job resource. The resource to be deleted is identified with the path component
        of the URI.
      parameters:
      - description: Identifies the measurement job to be deleted.
        explode: false
        in: path
        name: jobId
        required: true
        schema:
          $ref: '#/components/schemas/uri-Type'
        style: simple
      responses:
        "204":
          description: Success case ("204 No Content"). The measurement job resource
            has been deleted. The response message body is absent.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-ResponseType'
          description: Error case.
      summary: Delete a single measurement job
    get:
      description: "With HTTP GET, resource of a measurement job is read. The resource\
        \ to be read is identified with the path component of the URI."
      parameters:
      - description: Identifies the measurement job to be read.
        explode: false
        in: path
        name: jobId
        required: true
        schema:
          $ref: '#/components/schemas/uri-Type'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/measJobsRetrieval-ResponseType'
          description: 'Success case ("200 OK"). The resource identified in the path
            for retrieval is returned in the response message body. '
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-ResponseType'
          description: Error case.
      summary: Read resource of a single measurement job
components:
  schemas:
    dateTime-Type:
      format: date-Time
      type: string
    uri-Type:
      type: string
    measJobCreation-RequestType:
      properties:
        iOCName:
          type: string
        iOCInstanceList:
          items:
            $ref: '#/components/schemas/uri-Type'
          type: array
        measurementCategoryList:
          items:
            type: string
          type: array
        reportingMethod:
          $ref: '#/components/schemas/reportingMethod-Type'
        granularityPeriod:
          type: integer
        reportingPeriod:
          type: integer
        startTime:
          format: date-Time
          type: string
        stopTime:
          format: date-Time
          type: string
        schedule:
          $ref: '#/components/schemas/schedule-Type'
        streamTarget:
          type: string
        priority:
          $ref: '#/components/schemas/priority-Type'
        reliability:
          type: string
      type: object
    measJobCreation-ResponseType:
      example:
        unsupportedList:
        - measurementTypeName: measurementTypeName
          reason: reason
          iOCInstance: iOCInstance
        - measurementTypeName: measurementTypeName
          reason: reason
          iOCInstance: iOCInstance
      properties:
        unsupportedList:
          items:
            $ref: '#/components/schemas/unsupportedMeas-Type'
          type: array
      type: object
    measJobsRetrieval-ResponseType:
      example:
        jobInfoList:
        - reportingMethod: null
          reportingPeriod: 6
          reliability: reliability
          priority: null
          granularityPeriod: 0
          streamTarget: streamTarget
          schedule:
            dailySchedule:
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            scheduleOption: null
            weeklySchedule:
            - intervalsOfDay:
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              dayOfWeek: null
            - intervalsOfDay:
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              dayOfWeek: null
          measurementCategoryList:
          - measurementCategoryList
          - measurementCategoryList
          iOCName: iOCName
          iOCInstanceList:
          - null
          - null
          startTime: startTime
          stopTime: stopTime
          href: href
        - reportingMethod: null
          reportingPeriod: 6
          reliability: reliability
          priority: null
          granularityPeriod: 0
          streamTarget: streamTarget
          schedule:
            dailySchedule:
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            scheduleOption: null
            weeklySchedule:
            - intervalsOfDay:
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              dayOfWeek: null
            - intervalsOfDay:
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              - intervalEnd: intervalEnd
                intervalStart: intervalStart
              dayOfWeek: null
          measurementCategoryList:
          - measurementCategoryList
          - measurementCategoryList
          iOCName: iOCName
          iOCInstanceList:
          - null
          - null
          startTime: startTime
          stopTime: stopTime
          href: href
      properties:
        jobInfoList:
          items:
            $ref: '#/components/schemas/measJobInfo-ResourceType'
          type: array
      type: object
    error-ResponseType:
      properties:
        error:
          $ref: '#/components/schemas/error_ResponseType_error'
      type: object
    measJobInfo-ResourceType:
      example:
        reportingMethod: null
        reportingPeriod: 6
        reliability: reliability
        priority: null
        granularityPeriod: 0
        streamTarget: streamTarget
        schedule:
          dailySchedule:
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          scheduleOption: null
          weeklySchedule:
          - intervalsOfDay:
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            dayOfWeek: null
          - intervalsOfDay:
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            - intervalEnd: intervalEnd
              intervalStart: intervalStart
            dayOfWeek: null
        measurementCategoryList:
        - measurementCategoryList
        - measurementCategoryList
        iOCName: iOCName
        iOCInstanceList:
        - null
        - null
        startTime: startTime
        stopTime: stopTime
        href: href
      properties:
        href:
          type: string
        iOCName:
          type: string
        iOCInstanceList:
          items:
            $ref: '#/components/schemas/uri-Type'
          type: array
        measurementCategoryList:
          items:
            type: string
          type: array
        reportingMethod:
          $ref: '#/components/schemas/reportingMethod-Type'
        granularityPeriod:
          type: integer
        reportingPeriod:
          type: integer
        startTime:
          format: date-Time
          type: string
        stopTime:
          format: date-Time
          type: string
        schedule:
          $ref: '#/components/schemas/schedule-Type'
        streamTarget:
          type: string
        priority:
          $ref: '#/components/schemas/priority-Type'
        reliability:
          type: string
      type: object
    schedule-Type:
      example:
        dailySchedule:
        - intervalEnd: intervalEnd
          intervalStart: intervalStart
        - intervalEnd: intervalEnd
          intervalStart: intervalStart
        scheduleOption: null
        weeklySchedule:
        - intervalsOfDay:
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          dayOfWeek: null
        - intervalsOfDay:
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          - intervalEnd: intervalEnd
            intervalStart: intervalStart
          dayOfWeek: null
      properties:
        scheduleOption:
          $ref: '#/components/schemas/scheduleOption-Type'
        dailySchedule:
          items:
            $ref: '#/components/schemas/timeInterval-Type'
          type: array
        weeklySchedule:
          items:
            $ref: '#/components/schemas/scheduleOfDay-Type'
          type: array
      type: object
    timeInterval-Type:
      example:
        intervalEnd: intervalEnd
        intervalStart: intervalStart
      properties:
        intervalStart:
          format: Time
          type: string
        intervalEnd:
          format: Time
          type: string
      type: object
    scheduleOfDay-Type:
      example:
        intervalsOfDay:
        - intervalEnd: intervalEnd
          intervalStart: intervalStart
        - intervalEnd: intervalEnd
          intervalStart: intervalStart
        dayOfWeek: null
      properties:
        dayOfWeek:
          $ref: '#/components/schemas/dayOfWeek-Type'
        intervalsOfDay:
          items:
            $ref: '#/components/schemas/timeInterval-Type'
          type: array
      type: object
    unsupportedMeas-Type:
      example:
        measurementTypeName: measurementTypeName
        reason: reason
        iOCInstance: iOCInstance
      properties:
        iOCInstance:
          type: string
        measurementTypeName:
          type: string
        reason:
          type: string
      type: object
    reportingMethod-Type:
      enum:
      - file
      - streaming
      type: string
    priority-Type:
      enum:
      - low
      - medium
      - high
      type: string
    scheduleOption-Type:
      enum:
      - daily
      - weekly
      type: string
    dayOfWeek-Type:
      enum:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday
      type: string
    error_ResponseType_error:
      properties:
        errorInfo:
          type: string
      type: object
