/*
3gpp-acs-pp

API for 5G ACS Parameter Provision.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_ACSParameterProvision

import (
	"encoding/json"
)

// checks if the AcsConfigurationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcsConfigurationData{}

// AcsConfigurationData Represents an individual ACS Configuration subscription resource.
type AcsConfigurationData struct {
	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	Self *string `json:"self,omitempty"`
	// string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information.
	ExterGroupId *string `json:"exterGroupId,omitempty"`
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.
	Gpsi    *string `json:"gpsi,omitempty"`
	AcsInfo AcsInfo `json:"acsInfo"`
	// String uniquely identifying MTC provider information.
	MtcProviderId *string `json:"mtcProviderId,omitempty"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat string `json:"suppFeat"`
}

// NewAcsConfigurationData instantiates a new AcsConfigurationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcsConfigurationData(acsInfo AcsInfo, suppFeat string) *AcsConfigurationData {
	this := AcsConfigurationData{}
	this.AcsInfo = acsInfo
	this.SuppFeat = suppFeat
	return &this
}

// NewAcsConfigurationDataWithDefaults instantiates a new AcsConfigurationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcsConfigurationDataWithDefaults() *AcsConfigurationData {
	this := AcsConfigurationData{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *AcsConfigurationData) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *AcsConfigurationData) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *AcsConfigurationData) SetSelf(v string) {
	o.Self = &v
}

// GetExterGroupId returns the ExterGroupId field value if set, zero value otherwise.
func (o *AcsConfigurationData) GetExterGroupId() string {
	if o == nil || IsNil(o.ExterGroupId) {
		var ret string
		return ret
	}
	return *o.ExterGroupId
}

// GetExterGroupIdOk returns a tuple with the ExterGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetExterGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExterGroupId) {
		return nil, false
	}
	return o.ExterGroupId, true
}

// HasExterGroupId returns a boolean if a field has been set.
func (o *AcsConfigurationData) HasExterGroupId() bool {
	if o != nil && !IsNil(o.ExterGroupId) {
		return true
	}

	return false
}

// SetExterGroupId gets a reference to the given string and assigns it to the ExterGroupId field.
func (o *AcsConfigurationData) SetExterGroupId(v string) {
	o.ExterGroupId = &v
}

// GetGpsi returns the Gpsi field value if set, zero value otherwise.
func (o *AcsConfigurationData) GetGpsi() string {
	if o == nil || IsNil(o.Gpsi) {
		var ret string
		return ret
	}
	return *o.Gpsi
}

// GetGpsiOk returns a tuple with the Gpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetGpsiOk() (*string, bool) {
	if o == nil || IsNil(o.Gpsi) {
		return nil, false
	}
	return o.Gpsi, true
}

// HasGpsi returns a boolean if a field has been set.
func (o *AcsConfigurationData) HasGpsi() bool {
	if o != nil && !IsNil(o.Gpsi) {
		return true
	}

	return false
}

// SetGpsi gets a reference to the given string and assigns it to the Gpsi field.
func (o *AcsConfigurationData) SetGpsi(v string) {
	o.Gpsi = &v
}

// GetAcsInfo returns the AcsInfo field value
func (o *AcsConfigurationData) GetAcsInfo() AcsInfo {
	if o == nil {
		var ret AcsInfo
		return ret
	}

	return o.AcsInfo
}

// GetAcsInfoOk returns a tuple with the AcsInfo field value
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetAcsInfoOk() (*AcsInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcsInfo, true
}

// SetAcsInfo sets field value
func (o *AcsConfigurationData) SetAcsInfo(v AcsInfo) {
	o.AcsInfo = v
}

// GetMtcProviderId returns the MtcProviderId field value if set, zero value otherwise.
func (o *AcsConfigurationData) GetMtcProviderId() string {
	if o == nil || IsNil(o.MtcProviderId) {
		var ret string
		return ret
	}
	return *o.MtcProviderId
}

// GetMtcProviderIdOk returns a tuple with the MtcProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetMtcProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.MtcProviderId) {
		return nil, false
	}
	return o.MtcProviderId, true
}

// HasMtcProviderId returns a boolean if a field has been set.
func (o *AcsConfigurationData) HasMtcProviderId() bool {
	if o != nil && !IsNil(o.MtcProviderId) {
		return true
	}

	return false
}

// SetMtcProviderId gets a reference to the given string and assigns it to the MtcProviderId field.
func (o *AcsConfigurationData) SetMtcProviderId(v string) {
	o.MtcProviderId = &v
}

// GetSuppFeat returns the SuppFeat field value
func (o *AcsConfigurationData) GetSuppFeat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuppFeat
}

// GetSuppFeatOk returns a tuple with the SuppFeat field value
// and a boolean to check if the value has been set.
func (o *AcsConfigurationData) GetSuppFeatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuppFeat, true
}

// SetSuppFeat sets field value
func (o *AcsConfigurationData) SetSuppFeat(v string) {
	o.SuppFeat = v
}

func (o AcsConfigurationData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AcsConfigurationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.ExterGroupId) {
		toSerialize["exterGroupId"] = o.ExterGroupId
	}
	if !IsNil(o.Gpsi) {
		toSerialize["gpsi"] = o.Gpsi
	}
	toSerialize["acsInfo"] = o.AcsInfo
	if !IsNil(o.MtcProviderId) {
		toSerialize["mtcProviderId"] = o.MtcProviderId
	}
	toSerialize["suppFeat"] = o.SuppFeat
	return toSerialize, nil
}

type NullableAcsConfigurationData struct {
	value *AcsConfigurationData
	isSet bool
}

func (v NullableAcsConfigurationData) Get() *AcsConfigurationData {
	return v.value
}

func (v *NullableAcsConfigurationData) Set(val *AcsConfigurationData) {
	v.value = val
	v.isSet = true
}

func (v NullableAcsConfigurationData) IsSet() bool {
	return v.isSet
}

func (v *NullableAcsConfigurationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcsConfigurationData(val *AcsConfigurationData) *NullableAcsConfigurationData {
	return &NullableAcsConfigurationData{value: val, isSet: true}
}

func (v NullableAcsConfigurationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcsConfigurationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
