/*
Nnssaaf_AIW

AAA Interworking Authentication and Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.1.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_Nnssaaf_AIW

import (
	"encoding/json"
)

// checks if the AuthConfirmationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthConfirmationResponse{}

// AuthConfirmationResponse struct for AuthConfirmationResponse
type AuthConfirmationResponse struct {
	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. 
	Supi string `json:"supi"`
	// contains an EAP packet
	EapMessage NullableString `json:"eapMessage"`
	AuthResult *AuthStatus `json:"authResult,omitempty"`
	PvsInfo []ServerAddressingInfo `json:"pvsInfo,omitempty"`
	// Contains the Master Session Key.
	Msk *string `json:"msk,omitempty"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SupportedFeatures *string `json:"supportedFeatures,omitempty"`
}

// NewAuthConfirmationResponse instantiates a new AuthConfirmationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthConfirmationResponse(supi string, eapMessage NullableString) *AuthConfirmationResponse {
	this := AuthConfirmationResponse{}
	this.Supi = supi
	this.EapMessage = eapMessage
	return &this
}

// NewAuthConfirmationResponseWithDefaults instantiates a new AuthConfirmationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthConfirmationResponseWithDefaults() *AuthConfirmationResponse {
	this := AuthConfirmationResponse{}
	return &this
}

// GetSupi returns the Supi field value
func (o *AuthConfirmationResponse) GetSupi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Supi
}

// GetSupiOk returns a tuple with the Supi field value
// and a boolean to check if the value has been set.
func (o *AuthConfirmationResponse) GetSupiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Supi, true
}

// SetSupi sets field value
func (o *AuthConfirmationResponse) SetSupi(v string) {
	o.Supi = v
}

// GetEapMessage returns the EapMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuthConfirmationResponse) GetEapMessage() string {
	if o == nil || o.EapMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.EapMessage.Get()
}

// GetEapMessageOk returns a tuple with the EapMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthConfirmationResponse) GetEapMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EapMessage.Get(), o.EapMessage.IsSet()
}

// SetEapMessage sets field value
func (o *AuthConfirmationResponse) SetEapMessage(v string) {
	o.EapMessage.Set(&v)
}

// GetAuthResult returns the AuthResult field value if set, zero value otherwise.
func (o *AuthConfirmationResponse) GetAuthResult() AuthStatus {
	if o == nil || IsNil(o.AuthResult) {
		var ret AuthStatus
		return ret
	}
	return *o.AuthResult
}

// GetAuthResultOk returns a tuple with the AuthResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfirmationResponse) GetAuthResultOk() (*AuthStatus, bool) {
	if o == nil || IsNil(o.AuthResult) {
		return nil, false
	}
	return o.AuthResult, true
}

// HasAuthResult returns a boolean if a field has been set.
func (o *AuthConfirmationResponse) HasAuthResult() bool {
	if o != nil && !IsNil(o.AuthResult) {
		return true
	}

	return false
}

// SetAuthResult gets a reference to the given AuthStatus and assigns it to the AuthResult field.
func (o *AuthConfirmationResponse) SetAuthResult(v AuthStatus) {
	o.AuthResult = &v
}

// GetPvsInfo returns the PvsInfo field value if set, zero value otherwise.
func (o *AuthConfirmationResponse) GetPvsInfo() []ServerAddressingInfo {
	if o == nil || IsNil(o.PvsInfo) {
		var ret []ServerAddressingInfo
		return ret
	}
	return o.PvsInfo
}

// GetPvsInfoOk returns a tuple with the PvsInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfirmationResponse) GetPvsInfoOk() ([]ServerAddressingInfo, bool) {
	if o == nil || IsNil(o.PvsInfo) {
		return nil, false
	}
	return o.PvsInfo, true
}

// HasPvsInfo returns a boolean if a field has been set.
func (o *AuthConfirmationResponse) HasPvsInfo() bool {
	if o != nil && !IsNil(o.PvsInfo) {
		return true
	}

	return false
}

// SetPvsInfo gets a reference to the given []ServerAddressingInfo and assigns it to the PvsInfo field.
func (o *AuthConfirmationResponse) SetPvsInfo(v []ServerAddressingInfo) {
	o.PvsInfo = v
}

// GetMsk returns the Msk field value if set, zero value otherwise.
func (o *AuthConfirmationResponse) GetMsk() string {
	if o == nil || IsNil(o.Msk) {
		var ret string
		return ret
	}
	return *o.Msk
}

// GetMskOk returns a tuple with the Msk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfirmationResponse) GetMskOk() (*string, bool) {
	if o == nil || IsNil(o.Msk) {
		return nil, false
	}
	return o.Msk, true
}

// HasMsk returns a boolean if a field has been set.
func (o *AuthConfirmationResponse) HasMsk() bool {
	if o != nil && !IsNil(o.Msk) {
		return true
	}

	return false
}

// SetMsk gets a reference to the given string and assigns it to the Msk field.
func (o *AuthConfirmationResponse) SetMsk(v string) {
	o.Msk = &v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *AuthConfirmationResponse) GetSupportedFeatures() string {
	if o == nil || IsNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfirmationResponse) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.SupportedFeatures) {
		return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *AuthConfirmationResponse) HasSupportedFeatures() bool {
	if o != nil && !IsNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *AuthConfirmationResponse) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

func (o AuthConfirmationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthConfirmationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["supi"] = o.Supi
	toSerialize["eapMessage"] = o.EapMessage.Get()
	if !IsNil(o.AuthResult) {
		toSerialize["authResult"] = o.AuthResult
	}
	if !IsNil(o.PvsInfo) {
		toSerialize["pvsInfo"] = o.PvsInfo
	}
	if !IsNil(o.Msk) {
		toSerialize["msk"] = o.Msk
	}
	if !IsNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	return toSerialize, nil
}

type NullableAuthConfirmationResponse struct {
	value *AuthConfirmationResponse
	isSet bool
}

func (v NullableAuthConfirmationResponse) Get() *AuthConfirmationResponse {
	return v.value
}

func (v *NullableAuthConfirmationResponse) Set(val *AuthConfirmationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthConfirmationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthConfirmationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthConfirmationResponse(val *AuthConfirmationResponse) *NullableAuthConfirmationResponse {
	return &NullableAuthConfirmationResponse{value: val, isSet: true}
}

func (v NullableAuthConfirmationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthConfirmationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


