openapi: 3.0.1
info:
  description: "OAS 3.0.1 specification of common type definitions in the Generic\
    \ NRM © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA,\
    \ TTC). All rights reserved."
  title: Common Type Definitions
  version: 18.1.0
externalDocs:
  description: 3GPP TS 28.623; Generic NRM; Common type definitions
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.623/
servers:
- url: /
paths: {}
components:
  schemas:
    Float:
      format: float
      type: number
    DateTime:
      format: date-time
      type: string
    Latitude:
      format: float
      maximum: 90
      minimum: -90
      type: number
    Longitude:
      format: float
      maximum: 180
      minimum: -180
      type: number
    Dn:
      type: string
    DnList:
      items:
        $ref: '#/components/schemas/Dn'
      type: array
    Mcc:
      pattern: "^[0-9]{3}$"
      type: string
    Mnc:
      pattern: "^[0-9]{2,3}$"
      type: string
    Nid:
      pattern: "^[A-Fa-f0-9]{11}$"
      type: string
    PlmnId:
      properties:
        mcc:
          pattern: "^[0-9]{3}$"
          type: string
        mnc:
          pattern: "^[0-9]{2,3}$"
          type: string
      type: object
    Tac:
      pattern: "(^[A-Fa-f0-9]{4}$)|(^[A-Fa-f0-9]{6}$)"
      type: string
    UtraCellId:
      type: integer
    EutraCellId:
      pattern: "^[A-Fa-f0-9]{7}$"
      type: string
    NrCellId:
      pattern: "^[A-Fa-f0-9]{9}$"
      type: string
    TimeWindow:
      properties:
        startTime:
          format: date-time
          type: string
        endTime:
          format: date-time
          type: string
      type: object
    GeoCoordinate:
      properties:
        latitude:
          format: float
          maximum: 90
          minimum: -90
          type: number
        longitude:
          format: float
          maximum: 180
          minimum: -180
          type: number
      type: object
    ConvexGeoPolygon:
      items:
        $ref: '#/components/schemas/GeoCoordinate'
      minItems: 3
      type: array
    GeoArea:
      properties:
        convexGeoPolygon:
          items:
            $ref: '#/components/schemas/GeoCoordinate'
          minItems: 3
          type: array
      type: object
    GeoAreaToCellMapping:
      properties:
        geoArea:
          $ref: '#/components/schemas/GeoArea'
        associationThreshold:
          type: integer
      type: object
    AreaOfInterest:
      oneOf:
      - $ref: '#/components/schemas/GeoAreaToCellMapping'
      - items:
          $ref: '#/components/schemas/Tai'
        type: array
      - items:
          $ref: '#/components/schemas/NrCellId'
        type: array
      - items:
          $ref: '#/components/schemas/EutraCellId'
        type: array
      - items:
          $ref: '#/components/schemas/UtraCellId'
        type: array
    Fqdn:
      type: string
    Ipv4Addr:
      example: 198.51.100.1
      pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
      type: string
    Ipv6Addr:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$"
      example: 2001:db8:85a3::8a2e:370:7334
      type: string
    Ipv6Prefix:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\\\
          /(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\\\
          /.+)$"
      example: 2001:db8:abcd:12::0/64
      type: string
    IpAddr:
      oneOf:
      - $ref: '#/components/schemas/Ipv4Addr'
      - $ref: '#/components/schemas/Ipv6Addr'
    HostAddr:
      oneOf:
      - $ref: '#/components/schemas/Ipv4Addr'
      - $ref: '#/components/schemas/Ipv6Addr'
      - $ref: '#/components/schemas/Fqdn'
    Host:
      oneOf:
      - $ref: '#/components/schemas/IpAddr'
      - $ref: '#/components/schemas/Fqdn'
    Uri:
      type: string
    AdministrativeState:
      enum:
      - LOCKED
      - UNLOCKED
      type: string
    OperationalState:
      enum:
      - ENABLED
      - DISABLED
      type: string
    UsageState:
      enum:
      - IDEL
      - ACTIVE
      - BUSY
      type: string
    AttributeNameValuePairSet:
      additionalProperties:
        nullable: true
      description: "The key of this map is the attribute name, and the value the attribute\
        \ value."
      minProperties: 1
      type: object
    AttributeValueChangeSet:
      description: "The first array item contains the attribute name value pairs with\
        \ the new values, and the second array item the attribute name value pairs\
        \ with the optional old values."
      items:
        $ref: '#/components/schemas/AttributeNameValuePairSet'
      maxItems: 2
      minItems: 1
      type: array
    Filter:
      description: The filter format shall be compliant to XPath 1.0.
      type: string
    SystemDN:
      type: string
    NotificationId:
      type: integer
    NotificationType:
      oneOf:
      - $ref: '#/components/schemas/AlarmNotificationTypes'
      - $ref: '#/components/schemas/CmNotificationTypes'
      - $ref: '#/components/schemas/PerfNotificationTypes'
      - $ref: '#/components/schemas/HeartbeatNotificationTypes'
      - $ref: '#/components/schemas/FileNotificationTypes'
    NotificationHeader:
      properties:
        href:
          type: string
        notificationId:
          type: integer
        notificationType:
          $ref: '#/components/schemas/NotificationType'
        eventTime:
          format: date-time
          type: string
        systemDN:
          type: string
      required:
      - eventTime
      - href
      - notificationId
      - notificationType
      - systemDN
      type: object
    ErrorResponse:
      description: Default schema for the response message body in case the request
        is not successful.
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse_error'
      type: object
    Tai:
      properties:
        mcc:
          pattern: "^[0-9]{3}$"
          type: string
        mnc:
          pattern: "^[0-9]{2,3}$"
          type: string
        tac:
          pattern: "(^[A-Fa-f0-9]{4}$)|(^[A-Fa-f0-9]{6}$)"
          type: string
      type: object
    AlarmNotificationTypes:
      enum:
      - notifyNewAlarm
      - notifyChangedAlarm
      - notifyChangedAlarmGeneral
      - notifyAckStateChanged
      - notifyCorrelatedNotificationChanged
      - notifyComments
      - notifyClearedAlarm
      - notifyAlarmListRebuilt
      - notifyPotentialFaultyAlarmList
      type: string
    CmNotificationTypes:
      enum:
      - notifyMOICreation
      - notifyMOIDeletion
      - notifyMOIAttributeValueChanges
      - notifyMOIChanges
      type: string
    PerfNotificationTypes:
      enum:
      - notifyThresholdCrossing
      type: string
    HeartbeatNotificationTypes:
      enum:
      - notifyHeartbeat
      type: string
    FileNotificationTypes:
      enum:
      - notifyFileReady
      - notifyFilePreparationError
      type: string
    ErrorResponse_error:
      properties:
        errorInfo:
          type: string
      type: object
