openapi: 3.0.0
info:
  description: |
    5GMS AF M1 Server Certificates Provisioning API
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  title: M1_ServerCertificatesProvisioning
  version: 2.0.0
externalDocs:
  description: TS 26.512 V17.2.0; 5G Media Streaming (5GMS); Protocols
  url: https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/
servers:
- url: "{apiRoot}/3gpp-m1/v2"
  variables:
    apiRoot:
      default: https://example.com
      description: See 3GPP TS 29.512 clause 6.1.
tags:
- description: "5G Media Streaming: Provisioning (M1) APIs: Server Certificates Provisioning"
  name: M1_ServerCertificatesProvisioning
paths:
  /provisioning-sessions/{provisioningSessionId}/certificates:
    post:
      description: "Without the optional csr query parameter, an X.509 certificate\
        \ is generated and this is returned. If the csr query parameter is present,\
        \ a Certificate Signing Request is instead generated and returned, allowing\
        \ the X.509 certificate to be generated by the invoker and later uploaded."
      operationId: createOrReserveServerCertificate
      parameters:
      - description: The resource identifier of an existing Provisioning Session.'
        explode: false
        in: path
        name: provisioningSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      - description: "When present, return a Certificate Signing Request instead of\
          \ generating an X.509 certificate"
        explode: true
        in: query
        name: csr
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/x-pem-file:
              schema:
                type: string
          description: Server Certificate Created
          headers:
            Location:
              description: URL of the newly created Server Certificate resource
              explode: false
              required: true
              schema:
                $ref: '#/components/schemas/Url'
              style: simple
      summary: Create or reserve a Service Certificate resource
  /provisioning-sessions/{provisioningSessionId}/certificates/{certificateId}:
    delete:
      operationId: destroyServerCertificate
      parameters:
      - description: The resource identifier of an existing Provisioning Session.'
        explode: false
        in: path
        name: provisioningSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      - description: The resource identifier of an existing Server Certificate
        explode: false
        in: path
        name: certificateId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "204":
          description: Server Certificate Destroyed
      summary: Destroy an existing Server Certificate resource
    get:
      operationId: retrieveServerCertificate
      parameters:
      - description: The resource identifier of an existing Provisioning Session.'
        explode: false
        in: path
        name: provisioningSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      - description: The resource identifier of an existing Server Certificate
        explode: false
        in: path
        name: certificateId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "200":
          content:
            application/x-pem-file:
              schema:
                type: string
          description: Success
        "204":
          description: Awaiting Upload
        "404":
          description: Not Found
      summary: Retrieve the X.509 certificate representation of the specified Server
        Certificate resource
    put:
      operationId: uploadServerCertificate
      parameters:
      - description: The resource identifier of an existing Provisioning Session.'
        explode: false
        in: path
        name: provisioningSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      - description: The resource identifier of an existing Server Certificate
        explode: false
        in: path
        name: certificateId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      requestBody:
        content:
          application/x-pem-file:
            schema:
              type: string
        required: true
      responses:
        "204":
          description: Server Certificate Updated
      summary: Upload the X.509 certificate for a previously reserved Server Certificate
        resource
components:
  schemas:
    ResourceId:
      description: String chosen by the 5GMS AF to serve as an identifier in a resource
        URI.
      type: string
    Url:
      description: "Uniform Resource Locator, comforming with the URI Generic Syntax\
        \ specified in IETF RFC 3986."
      format: uri
      type: string
