openapi: 3.0.0
info:
  description: |
    5GMS AF M5 Network Assistance API
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  title: M5_NetworkAssistance
  version: 2.0.0
externalDocs:
  description: 3GPP TS 26.512 V17.2.0; 5G Media Streaming (5GMS); Protocols.
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/26.512/
servers:
- url: "{apiRoot}/3gpp-m5/v2"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in subclause 4.4.1 of 3GPP TS 29.501.
tags:
- description: "5G Media Streaming: Media Session Handling (M5) APIs: Network Assistance"
  name: M5_NetworkAssistance
paths:
  /network-assistance/:
    post:
      operationId: createNetworkAssistanceSession
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkAssistanceSession'
          description: Created Network Assistance Session
          headers:
            Location:
              description: The URL of the nely created Network Assistance Session
                resource
              explode: false
              required: true
              schema:
                $ref: '#/components/schemas/Url'
              style: simple
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Create a new Network Assistance Session.
  /network-assistance/{naSessionId}:
    delete:
      operationId: destroyNetworkAssistanceSession
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "204":
          description: Destroyed Network Assistance Session
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Destroy an existing Network Assistance Session resource
    get:
      operationId: retrieveNetworkAssistanceSession
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkAssistanceSession'
          description: A JSON representation of a Network Assistance Session resource
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Retrieve an existing Network Assistance Session resource
    patch:
      operationId: patchNetworkAssistanceSession
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/NetworkAssistanceSession'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/NetworkAssistanceSession'
        description: A JSON patch to a Network Assistance Session resource
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkAssistanceSession'
          description: Patched Network Assistance Session
        "204":
          description: Patched Network Assistance Session
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Patch an existing Network Assistance Session resource
    put:
      operationId: updateNetworkAssistanceSession
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAssistanceSession'
        description: A replacement JSON representation of a Network Assistance Session
          resource
        required: true
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Update an existing Network Assistance Session resource
  /network-assistance/{naSessionId}/recommendation:
    get:
      operationId: requestBitRateRecommendation
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/M5QoSSpecification'
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Obtain a bit rate recommendation for the next recommendation window
  /network-assistance/{naSessionId}/boost-request:
    post:
      operationId: requestDeliveryBoost
      parameters:
      - description: The resource identifier of an existing Network Assistance Session
          resource
        explode: false
        in: path
        name: naSessionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationSuccessResponse'
          description: Delivery Boost Request Processed
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Request a delivery boost
components:
  schemas:
    NetworkAssistanceSession:
      description: A representation of a Network Assistance Session resource.
      example:
        notficationURL: https://openapi-generator.tech
        recommendedQoS:
          mirBwUlBitRate: mirBwUlBitRate
          marBwUlBitRate: marBwUlBitRate
          desLoss: 0
          marBwDlBitRate: marBwDlBitRate
          mirBwDlBitRate: mirBwDlBitRate
          desLatency: 0
          minDesBwUlBitRate: minDesBwUlBitRate
          minDesBwDlBitRate: minDesBwDlBitRate
        naSessionId: naSessionId
        requestedQoS:
          mirBwUlBitRate: mirBwUlBitRate
          marBwUlBitRate: marBwUlBitRate
          desLoss: 0
          marBwDlBitRate: marBwDlBitRate
          mirBwDlBitRate: mirBwDlBitRate
          desLatency: 0
          minDesBwUlBitRate: minDesBwUlBitRate
          minDesBwDlBitRate: minDesBwDlBitRate
        policyTemplateId: policyTemplateId
        serviceDataFlowDescription:
        - domainName: domainName
          flowDescription:
            toSTc: toSTc
            srcIp: srcIp
            protocol: 0
            flowLabel: 5
            dstPort: 1
            dstIp: dstIp
            srcPort: 6
            spi: 5
            direction: direction
        - domainName: domainName
          flowDescription:
            toSTc: toSTc
            srcIp: srcIp
            protocol: 0
            flowLabel: 5
            dstPort: 1
            dstIp: dstIp
            srcPort: 6
            spi: 5
            direction: direction
      properties:
        naSessionId:
          description: String chosen by the 5GMS AF to serve as an identifier in a
            resource URI.
          type: string
        serviceDataFlowDescription:
          items:
            $ref: '#/components/schemas/ServiceDataFlowDescription'
          minItems: 1
          type: array
        policyTemplateId:
          description: String chosen by the 5GMS AF to serve as an identifier in a
            resource URI.
          type: string
        requestedQoS:
          $ref: '#/components/schemas/M5QoSSpecification'
        recommendedQoS:
          $ref: '#/components/schemas/M5QoSSpecification'
        notficationURL:
          description: "Uniform Resource Locator, comforming with the URI Generic\
            \ Syntax specified in IETF RFC 3986."
          format: uri
          type: string
      required:
      - naSessionId
      type: object
    Url:
      description: "Uniform Resource Locator, comforming with the URI Generic Syntax\
        \ specified in IETF RFC 3986."
      format: uri
      type: string
    ResourceId:
      description: String chosen by the 5GMS AF to serve as an identifier in a resource
        URI.
      type: string
    M5QoSSpecification:
      example:
        mirBwUlBitRate: mirBwUlBitRate
        marBwUlBitRate: marBwUlBitRate
        desLoss: 0
        marBwDlBitRate: marBwDlBitRate
        mirBwDlBitRate: mirBwDlBitRate
        desLatency: 0
        minDesBwUlBitRate: minDesBwUlBitRate
        minDesBwDlBitRate: minDesBwDlBitRate
      properties:
        marBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        marBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        minDesBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        minDesBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        mirBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        mirBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        desLatency:
          minimum: 0
          type: integer
        desLoss:
          minimum: 0
          type: integer
      required:
      - marBwDlBitRate
      - marBwUlBitRate
      - mirBwDlBitRate
      - mirBwUlBitRate
      type: object
    OperationSuccessResponse:
      example:
        reason: reason
        success: true
      properties:
        success:
          type: boolean
        reason:
          type: string
      required:
      - success
      type: object
    ServiceDataFlowDescription:
      example:
        domainName: domainName
        flowDescription:
          toSTc: toSTc
          srcIp: srcIp
          protocol: 0
          flowLabel: 5
          dstPort: 1
          dstIp: dstIp
          srcPort: 6
          spi: 5
          direction: direction
      properties:
        flowDescription:
          $ref: '#/components/schemas/IpPacketFilterSet'
        domainName:
          type: string
      type: object
    IpPacketFilterSet:
      example:
        toSTc: toSTc
        srcIp: srcIp
        protocol: 0
        flowLabel: 5
        dstPort: 1
        dstIp: dstIp
        srcPort: 6
        spi: 5
        direction: direction
      properties:
        srcIp:
          type: string
        dstIp:
          type: string
        protocol:
          type: integer
        srcPort:
          type: integer
        dstPort:
          type: integer
        toSTc:
          type: string
        flowLabel:
          type: integer
        spi:
          type: integer
        direction:
          type: string
      required:
      - direction
      type: object
    BitRate:
      description: |
        String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
      pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
      type: string
