openapi: 3.0.1
info:
  description: "OAS 3.0.1 definition of the File Data Reporting MnS © 2021, 3GPP Organizational\
    \ Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved."
  title: File Data Reporting MnS
  version: 17.1.0
externalDocs:
  description: 3GPP TS 28.532; Generic management services
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.532/
servers:
- url: "{MnSRoot}/fileDataReportingMnS/{MnSVersion}"
  variables:
    MnSRoot:
      default: http://example.com/3GPPManagement
      description: See clause 4.4.3 of TS 32.158
    MnSVersion:
      default: XXX
      description: Version number of the OpenAPI definition
paths:
  /files:
    get:
      description: "Information about available files is read with HTTP GET. The files\
        \ for which information shall be returned are identified with the path component\
        \ (base resource) and the query component (fileDataType, beginTime, endTime)\
        \ of the URI."
      parameters:
      - description: This parameter selects files based on the file data type.
        explode: true
        in: query
        name: fileDataType
        required: true
        schema:
          $ref: '#/components/schemas/FileDataType'
        style: form
      - description: This parameter selects files based on the earliest time they
          became available
        explode: true
        in: query
        name: beginTime
        required: false
        schema:
          $ref: '#/components/schemas/DateTime'
        style: form
      - description: This parameter selects files based on the latest time they became
          available
        explode: true
        in: query
        name: endTime
        required: false
        schema:
          $ref: '#/components/schemas/DateTime'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FileInfo'
                type: array
          description: '''Success case ("200 OK"). The resources identified in the
            request for retrieval are returned in the response message body.'''
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Read information about available files
  /subscriptions:
    post:
      callbacks:
        notifyFileReady:
          '{request.body#/consumerReference}':
            post:
              operationId: notifyFileReady_request_bodyConsumerReferencePost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NotifyFileReady'
                required: true
              responses:
                "204":
                  description: Success case ("204 No Content"). The notification is
                    successfully delivered. The response message body is absent.
                default:
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/ErrorResponse'
                  description: Error case.
              x-callback-request: true
        notifyFilePreparationError:
          '{request.body#/consumerReference}':
            post:
              operationId: notifyFilePreparationError_request_bodyConsumerReferencePost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NotifyFilePreparationError'
                required: true
              responses:
                "204":
                  description: Success case ("204 No Content"). The notification is
                    successfully delivered. The response message body is absent.
                default:
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/ErrorResponse'
                  description: Error case.
              x-callback-request: true
      description: To create a subscription the representation of the subscription
        is POSTed on the /subscriptions collection resource.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
          description: Success case ("201 Created"). The representation of the newly
            created subscription resource shall be returned.
          headers:
            Location:
              description: URI of the newly created subscription resource
              explode: false
              required: true
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Create a subscription
  /subscriptions/{subscriptionId}:
    delete:
      description: The subscription is deleted by deleting the corresponding subscription
        resource. The resource to be deleted is identified with the path component
        of the URI.
      parameters:
      - description: Identifies the subscription to be deleted.
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Success case ("204 No Content"). The subscription resource
            has been deleted. The response message body is absent.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Delete a subscription
components:
  schemas:
    FileDataType:
      enum:
      - Performance
      - Trace
      - Anatytics
      - Proprietary
      type: string
    FileNotificationTypes:
      enum:
      - notifyFileReady
      - notifyFilePreparationError
      type: string
    FileInfo:
      example:
        fileSize: 0
        fileLocation: fileLocation
        fileReadyTime: 2000-01-23T04:56:07.000+00:00
        fileFormat: fileFormat
        fileDataType: null
        fileExpirationTime: 2000-01-23T04:56:07.000+00:00
        fileCompression: fileCompression
      properties:
        fileLocation:
          type: string
        fileSize:
          type: integer
        fileReadyTime:
          format: date-time
          type: string
        fileExpirationTime:
          format: date-time
          type: string
        fileCompression:
          type: string
        fileFormat:
          type: string
        fileDataType:
          $ref: '#/components/schemas/FileDataType'
      type: object
    NotifyFileReady:
      allOf:
      - $ref: '#/components/schemas/NotificationHeader'
      - $ref: '#/components/schemas/NotifyFileReady_allOf'
    NotifyFilePreparationError:
      allOf:
      - $ref: '#/components/schemas/NotificationHeader'
      - $ref: '#/components/schemas/NotifyFilePreparationError_allOf'
    DateTime:
      format: date-time
      type: string
    ErrorResponse:
      description: Default schema for the response message body in case the request
        is not successful.
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse_error'
      type: object
    Subscription:
      example:
        filter: filter
        timeTick: 0
        consumerReference: consumerReference
      properties:
        consumerReference:
          type: string
        timeTick:
          type: integer
        filter:
          description: The filter format shall be compliant to XPath 1.0.
          type: string
      type: object
    Uri:
      type: string
    NotificationHeader:
      properties:
        href:
          type: string
        notificationId:
          type: integer
        notificationType:
          $ref: '#/components/schemas/NotificationType'
        eventTime:
          format: date-time
          type: string
        systemDN:
          type: string
      required:
      - eventTime
      - href
      - notificationId
      - notificationType
      - systemDN
      type: object
    NotificationId:
      type: integer
    NotificationType:
      oneOf:
      - $ref: '#/components/schemas/AlarmNotificationTypes'
      - $ref: '#/components/schemas/CmNotificationTypes'
      - $ref: '#/components/schemas/PerfNotificationTypes'
      - $ref: '#/components/schemas/HeartbeatNotificationTypes'
      - $ref: '#/components/schemas/FileNotificationTypes'
    SystemDN:
      type: string
    Filter:
      description: The filter format shall be compliant to XPath 1.0.
      type: string
    AlarmNotificationTypes:
      enum:
      - notifyNewAlarm
      - notifyChangedAlarm
      - notifyChangedAlarmGeneral
      - notifyAckStateChanged
      - notifyCorrelatedNotificationChanged
      - notifyComments
      - notifyClearedAlarm
      - notifyAlarmListRebuilt
      - notifyPotentialFaultyAlarmList
      type: string
    CmNotificationTypes:
      enum:
      - notifyMOICreation
      - notifyMOIDeletion
      - notifyMOIAttributeValueChanges
      - notifyMOIChanges
      type: string
    PerfNotificationTypes:
      enum:
      - notifyThresholdCrossing
      type: string
    HeartbeatNotificationTypes:
      enum:
      - notifyHeartbeat
      type: string
    NotifyFileReady_allOf:
      properties:
        fileInfoList:
          items:
            $ref: '#/components/schemas/FileInfo'
          type: array
        additionalText:
          type: string
      type: object
      example: null
    NotifyFilePreparationError_allOf:
      properties:
        fileInfoList:
          items:
            $ref: '#/components/schemas/FileInfo'
          type: array
        reason:
          type: string
        additionalText:
          type: string
      type: object
      example: null
    ErrorResponse_error:
      properties:
        errorInfo:
          type: string
      type: object
