openapi: 3.0.0
info:
  description: |
    5GMS AF M5 Dynamic Policy API
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  title: M5_DynamicPolicies
  version: 2.0.0
externalDocs:
  description: TS 26.512 V17.2.0; 5G Media Streaming (5GMS); Protocols
  url: https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/
servers:
- url: "{apiRoot}/3gpp-m5/v2"
  variables:
    apiRoot:
      default: https://example.com
      description: See 3GPP TS 29.512 clause 6.1.
tags:
- description: "5G Media Streaming: Media Session Handling (M5) APIs: Dynamic Policies"
  name: M5_DynamicPolicies
paths:
  /dynamic-policies:
    post:
      operationId: createDynamicPolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DynamicPolicy'
        description: An optional JSON representation of a Dynamic Policy resource
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicPolicy'
          description: Created Dynamic Policy Resource
          headers:
            Location:
              description: The URL of the newly created Dynamic Policy resource
              explode: false
              required: true
              schema:
                $ref: '#/components/schemas/Url'
              style: simple
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Create (and optionally upload) a new Dynamic Policy resource
  /dynamic-policies/{dynamicPolicyId}:
    delete:
      operationId: destroyDynamicPolicy
      parameters:
      - description: The resource identifier of a Dynamic Policy resource
        explode: false
        in: path
        name: dynamicPolicyId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "204":
          description: Destroyed Dynamic Policy
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Destroy an existing Dynamic Policy resource
    get:
      operationId: retrieveDynamicPolicy
      parameters:
      - description: The resource identifier of a Dynamic Policy resource
        explode: false
        in: path
        name: dynamicPolicyId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicPolicy'
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Retrieve an existing Dynamic Policy resource
    patch:
      operationId: patchDynamicPolicy
      parameters:
      - description: The resource identifier of a Dynamic Policy resource
        explode: false
        in: path
        name: dynamicPolicyId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/DynamicPolicy'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/DynamicPolicy'
        description: A JSON patch to a Dynamic Policy resource
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicPolicy'
          description: Patched Dynamic Policy
        "204":
          description: Patched Dynamic Policy
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Patch an existing Dynamic Policy resource
    put:
      operationId: updateDynamicPolicy
      parameters:
      - description: The resource identifier of a Dynamic Policy resource
        explode: false
        in: path
        name: dynamicPolicyId
        required: true
        schema:
          $ref: '#/components/schemas/ResourceId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DynamicPolicy'
        description: A replacement JSON representation of a Dynamic Policy resource
        required: true
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Update an existing Dynamic Policy resource
components:
  schemas:
    DynamicPolicy:
      description: A representation of a Dynamic Policy resource.
      example:
        enforcementBitRate: 9
        enforcementMethod: enforcementMethod
        provisioningSessionId: provisioningSessionId
        dynamicPolicyId: dynamicPolicyId
        policyTemplateId: policyTemplateId
        serviceDataFlowDescriptions:
        - domainName: domainName
          flowDescription:
            toSTc: toSTc
            srcIp: srcIp
            protocol: 0
            flowLabel: 5
            dstPort: 1
            dstIp: dstIp
            srcPort: 6
            spi: 5
            direction: direction
        - domainName: domainName
          flowDescription:
            toSTc: toSTc
            srcIp: srcIp
            protocol: 0
            flowLabel: 5
            dstPort: 1
            dstIp: dstIp
            srcPort: 6
            spi: 5
            direction: direction
        qosSpecification:
          mirBwUlBitRate: mirBwUlBitRate
          marBwUlBitRate: marBwUlBitRate
          desLoss: 0
          marBwDlBitRate: marBwDlBitRate
          mirBwDlBitRate: mirBwDlBitRate
          desLatency: 0
          minDesBwUlBitRate: minDesBwUlBitRate
          minDesBwDlBitRate: minDesBwDlBitRate
      properties:
        dynamicPolicyId:
          description: String chosen by the 5GMS AF to serve as an identifier in a
            resource URI.
          type: string
        policyTemplateId:
          description: String chosen by the 5GMS AF to serve as an identifier in a
            resource URI.
          type: string
        serviceDataFlowDescriptions:
          items:
            $ref: '#/components/schemas/ServiceDataFlowDescription'
          type: array
        provisioningSessionId:
          description: String chosen by the 5GMS AF to serve as an identifier in a
            resource URI.
          type: string
        qosSpecification:
          $ref: '#/components/schemas/M5QoSSpecification'
        enforcementMethod:
          type: string
        enforcementBitRate:
          type: integer
      required:
      - dynamicPolicyId
      - policyTemplateId
      - provisioningSessionId
      - serviceDataFlowDescriptions
      type: object
    Url:
      description: "Uniform Resource Locator, comforming with the URI Generic Syntax\
        \ specified in IETF RFC 3986."
      format: uri
      type: string
    ResourceId:
      description: String chosen by the 5GMS AF to serve as an identifier in a resource
        URI.
      type: string
    ServiceDataFlowDescription:
      example:
        domainName: domainName
        flowDescription:
          toSTc: toSTc
          srcIp: srcIp
          protocol: 0
          flowLabel: 5
          dstPort: 1
          dstIp: dstIp
          srcPort: 6
          spi: 5
          direction: direction
      properties:
        flowDescription:
          $ref: '#/components/schemas/IpPacketFilterSet'
        domainName:
          type: string
      type: object
    IpPacketFilterSet:
      example:
        toSTc: toSTc
        srcIp: srcIp
        protocol: 0
        flowLabel: 5
        dstPort: 1
        dstIp: dstIp
        srcPort: 6
        spi: 5
        direction: direction
      properties:
        srcIp:
          type: string
        dstIp:
          type: string
        protocol:
          type: integer
        srcPort:
          type: integer
        dstPort:
          type: integer
        toSTc:
          type: string
        flowLabel:
          type: integer
        spi:
          type: integer
        direction:
          type: string
      required:
      - direction
      type: object
    M5QoSSpecification:
      example:
        mirBwUlBitRate: mirBwUlBitRate
        marBwUlBitRate: marBwUlBitRate
        desLoss: 0
        marBwDlBitRate: marBwDlBitRate
        mirBwDlBitRate: mirBwDlBitRate
        desLatency: 0
        minDesBwUlBitRate: minDesBwUlBitRate
        minDesBwDlBitRate: minDesBwDlBitRate
      properties:
        marBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        marBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        minDesBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        minDesBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        mirBwDlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        mirBwUlBitRate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        desLatency:
          minimum: 0
          type: integer
        desLoss:
          minimum: 0
          type: integer
      required:
      - marBwDlBitRate
      - marBwUlBitRate
      - mirBwDlBitRate
      - mirBwUlBitRate
      type: object
    BitRate:
      description: |
        String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
      pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
      type: string
